name: "Lint"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  format-and-type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.13"

      - name: Install dependencies
        run: uv pip install --system  -e ".[lint]"

      - name: Check code formatting
        run: uv run ruff format --check .

      - name: Run linter
        run: uv run ruff check .

      - name: Type checking
        run: uv run mypy --pretty --no-error-summary .
