name: "Lint"

on:
  push: # Run on pushes to the default branch
    branches: [main]
  pull_request: # Also run on pull requests originated from forks
    branches: [main]

# This allows a subsequently queued workflow run to interrupt and cancel previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  Authorize:
    environment: ${{ github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name != github.repository &&
      'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: true

  format-and-type-check:
    needs: Authorize
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.13"

      - name: Install dependencies
        run: uv pip install --system  -e ".[lint]"

      - name: Check code formatting
        run: uv run ruff format --check .

      - name: Run linter
        run: uv run ruff check .

      - name: Type checking
        run: uv run mypy --pretty --no-error-summary .
