name: "Unit Tests"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.13"

      - name: Create venv
        run: uv venv .venv && source .venv/bin/activate && uv pip install -e ".[tests]"

      - name: Run Unit Tests
        run: source .venv/bin/activate && pytest -vvv -m unit tests/unit
